language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26

  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-26

script:
  - chmod +x ./gradlew